services:
  ml:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/ml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
